#  /—-------/   /-------/   |-------|
#  /       /    /       /   |       |
#  /-------     /       /   |--------
#  / \          /       /   |       \
# /    \        /       /   |       |
#/       \      /       /   |-------

# 插件版本请勿修改
ver: 1.0
tips: "[RCP公告]二十四字核心价值观：富强 民主 文明 和谐 自由 平等 公正 法制 爱国 敬业 诚信 友善"